### ISSUE TITLE
Tink state fails to compile with haxe 4.2

### ISSUE THREAD

**Issue by FrancisBourre** [HaxeFoundation/try.haxe.org#10]
Tink state fails to compile with haxe 4.2

`/tink_state/0.11.1/haxelib/src/tink/state/Promised.hx:15: characters 7-34 : error: Dynamic should be next.B
/tink_state/0.11.1/haxelib/src/tink/state/Promised.hx:15: characters 7-34 : ... have: tink.core.Promise<Dynamic>
/tink_state/0.11.1/haxelib/src/tink/state/Promised.hx:15: characters 7-34 : ... want: tink.Promise<next.B>
/tink_state/0.11.1/haxelib/src/tink/state/Observable.hx:71: characters 34-41 : Invalid call to static function flatten through abstract instance`

To be able to compile you must use haxe 4.1

**Comment by AlexHaxe** [comment]
I've upgraded tink_core and tink_state to github versions, it seems to work for Haxe 4.0-4.2. 
it doesn't work for Haxe 3 and also not for nightlies (which is probably a little bit concerning; maybe test locally and potentially raise an issue).
if there is a combination of versions or branches that works better, let me know and I will install them.

**Comment by AlexHaxe** [comment]
I guess it works, so I'm closing the issue. feel free to reopen.
