### ISSUE TITLE
Tracing type with $type does nothing

### ISSUE THREAD

**Issue by johhnry** [HaxeFoundation/try.haxe.org#15]
Hi,

From the [Tracing Types](https://haxe.org/manual/debugging-type-function.html) documentation page, I can use `$type(...)` to debug a type at compile time.

If I run this code in try.haxe.org, nothing appear in the output panel:

```haxe
class Test {
	static function main() {
		var myValue = "foo";
		$type(myValue); // String
	}
}
```

Is the feature available?

Thanks!

**Comment by AlexHaxe** [comment]
`Output` panel shows output from running the program. 
`$type` is (as you mention) a compile time thing. that's why it goes to `Compiler output` panel.

**Comment by johhnry** [comment]
@AlexHaxe My bad sorry, I didn't see it thanks!
