### ISSUE TITLE
Mobile: broken menu button

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/try.haxe.org#2]
Can be reproduced in responsive mode.
Can be compared with https://getbootstrap.com/docs/3.4/examples/navbar/
Can be related to bootstrap update...

**Comment by AlexHaxe** [comment]
yeah, taking bootstrap.js from local install and bootstrap.css from haxe.org site breaks mobile navigation.
quick fix would be to use haxe.org versions for both js and css. 

using local bootstrap.css breaks all kinds of styles and requires some more work

**Comment by AlexHaxe** [comment]
> quick fix would be to use haxe.org versions for both js and css.
which breaks Examples menu... :(

**Comment by AlexHaxe** [comment]
I guess we need to look into migrating bootstrap 2 to 3 and fix navigation and layout. but from a short look that requires a few hours of tweaking, testing and refactoring to make it look like the current version. not sure when I'll find the time to look into it.

if you have a small fix that makes mobile work with current bootstrap version check it in, I'll upload it tomorrow.
