### ISSUE TITLE
Hashlink target does not work

### ISSUE THREAD

**Issue by anissen** [HaxeFoundation/try.haxe.org#7]
I was quite surprised to see Hashlink in the targets list. 

Running with the Hashlink target (unsurprisingly?) results in an error. The error is as follows:
```
timeout: failed to run command '/opt/hashlink/hl': No such file or directory
```

**Comment by AlexHaxe** [comment]
I guess that broke when I added some very old Haxe versions. should be fixed now.

**Comment by anissen** [comment]
It works! Thanks 👍🏻
